### ISSUE TITLE
Detection and OCR networks convertion fails with SDK 3.8.1

### ISSUE THREAD

**Issue by asmorkalov** [GreenWaves-Technologies/licence_plate_recognition#2]
Log:
```
alexander@paradox:~/licence_plate_recognition$ make -f lprnet.mk clean model
Building GAP8 mode with 8 bit quantization
APP_SRCS... lprnet.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/libs/gap_lib/img_io/ImgIO.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Activation_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Bias_Linear_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Conv_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Pooling_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Conv_DW_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_MatAlgebra_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_SoftMax_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_AT_Misc.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/RNN_SQ8.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries/SSD_BasicKernels.c /mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/nntool/autotiler/kernels/norm_transpose.c BUILD_MODEL_LPR/lprnetKernels.c
APP_CFLAGS... -O3 -I. -I/mnt/projects/Projects/Xperience/GAP8/gap_sdk/libs/gap_lib/include -I/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/Emulation -I/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/Autotiler -I/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries -I/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8 -I/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/nntool/autotiler/kernels  -IBUILD_MODEL_LPR -DHAVE_LCD -DPERF -DSTACK_SIZE=6096 -DSLAVE_STACK_SIZE=1024 -DAT_IMAGE=/mnt/projects/Projects/licence_plate_recognition/images/china_1_cropped.ppm -DFREQ_CL=50 -DFREQ_FC=250 -DAT_INPUT_HEIGHT_SSD=240 -DAT_INPUT_WIDTH_SSD=320 -DAT_INPUT_COLORS_SSD=3 -DAT_INPUT_HEIGHT_LPR=24 -DAT_INPUT_WIDTH_LPR=94 -DAT_INPUT_COLORS_LPR=3
rm -f /home/alexander/licence_plate_recognition/BUILD/GAP8_V2/GCC_RISCV/flash.img
echo "GENERATING NNTOOL STATE FILE"
GENERATING NNTOOL STATE FILE
nntool -s model/nntool_script_lprnet BUILD_MODEL_LPR/lprnet.tflite -q
-s is not a recognized command, alias, or macro
model/nntool_script_lprnet is not a recognized command, alias, or macro
BUILD_MODEL_LPR/lprnet.tflite is not a recognized command, alias, or macro
-q is not a recognized command, alias, or macro
open - opening graph file BUILD_MODEL_LPR/lprnet.tflite
tflite - Importing TFLITE model version 3
EXCEPTION of type 'ValueError' occurred with message: 'no handler found for LOGISTIC'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
l2_ram_ext_managed - was: True
now: False
graph_reorder_constant_in - was: True
now: False
graph_size_opt - was: 0
now: 2
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
A graph must be opened to use this command. Use the open command to open a graph.
'
To enable full traceback, run the following command: 'set debug true'
echo "GENERATING AUTOTILER MODEL"
GENERATING AUTOTILER MODEL
nntool -g -M BUILD_MODEL_LPR -m lprnetModel.c -T BUILD_MODEL_LPR/tensors -H lprnetInfo.h   BUILD_MODEL_LPR/lprnet.json
Traceback (most recent call last):
  File "/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/nntool/nntool", line 105, in <module>
    main()
  File "/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/nntool/nntool", line 89, in main
    mod.generate_code(args)
  File "/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/nntool/interpreter/generator.py", line 67, in generate_code
    G, opts = load_state(args.graph_file, return_extra=True)
  File "/mnt/projects/Projects/Xperience/GAP8/gap_sdk/tools/nntool/utils/new_param_state.py", line 130, in load_state
    raise ValueError("state file not found")
ValueError: state file not found
common/model_rules.mk:71: recipe for target 'BUILD_MODEL_LPR/lprnetModel.c' failed
make: *** [BUILD_MODEL_LPR/lprnetModel.c] Error 1

```

**Comment by asmorkalov** [comment]
The demo works with SDK branch 3.8.0_dev

**Comment by Pafrak** [comment]
should be fixed now! Can you try it again?

**Comment by asmorkalov** [comment]
Yes, it works with SDK 3.9.1. Thanks!
